version: "3.8"
services: 
    client:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - "/app/node_modules"
            - "./:/app"
    
    test:
        container_name: lazyload-app-test
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "/app/node_modules"
            - "./:/app"
        environment: 
            - CI=true
        command: npm test

    prod:
        container_name: lazyload-app-prod
        build:
            context: .
            dockerfile: production.Dockerfile
        ports:
            - '3000:80'
        environment:
            - NODE_ENV=production
